### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by andreasdc** [HyperCubeMC/connected-block-textures#11]
doesn't work

**Comment by ghost** [comment]
Can confirm
![2021-08-13_20 11 04](https://user-images.githubusercontent.com/10375754/129402575-d14ed522-ba71-4a71-b46f-6d1a2cc16862.png)

(also tested without shaders)

**Comment by nerd** [comment]
try installing indium

**Comment by andreasdc** [comment]
How to install indium with sodium?

**Comment by andreasdc** [comment]
It works with Indium :)
