### ISSUE TITLE
Stained Glass can create visual bug

### ISSUE THREAD

**Issue by burneikis** [HyperCubeMC/connected-block-textures#12]
![2021-08-16_11 07 02](https://user-images.githubusercontent.com/87457198/129498783-aa4f420e-94e3-48d9-a5dd-099c4dda1df1.png)
When looking through stained glass at water columns and other glass this visual bug can occur.

**Comment by InterstellarHit** [comment]
I've found that this is a sodium issue and not an issue with connected textures.
